from __future__ import annotations

from typing import Any, Protocol


class Backend(Protocol):
    """Minimal array backend protocol for simulator linear algebra.

    This intentionally excludes RNG for Phase 1 to keep migration low risk.
    """

    name: str
    is_gpu: bool

    def array(self, data: Any, dtype: Any | None = None) -> Any: ...
    def zeros(self, shape: tuple[int, ...], dtype: Any | None = None) -> Any: ...
    def diag(self, a: Any) -> Any: ...
    def hstack(self, arrays: list[Any] | tuple[Any, ...]) -> Any: ...
    def vstack(self, arrays: list[Any] | tuple[Any, ...]) -> Any: ...
    def matmul(self, a: Any, b: Any) -> Any: ...
    def conj(self, a: Any) -> Any: ...
    def transpose(self, a: Any) -> Any: ...
    def real(self, a: Any) -> Any: ...
    def clip(self, a: Any, a_min: float, a_max: float) -> Any: ...
    def copy(self, a: Any) -> Any: ...
    def asnumpy(self, a: Any) -> Any: ...
